name: Build

on: [workflow_dispatch, push, pull_request]

jobs:
  build-macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: |
          brew install fltk pixman ffmpeg
          brew install gnutls nettle gmp
      - name: Configure
        run: cmake -DCMAKE_BUILD_PARALLEL_LEVEL=128 -DCMAKE_BUILD_TYPE=Release -S . -B build
      - name: Build
        working-directory: build
        run: make -j128
      - name: Install
        working-directory: build
        run: make dmg
      - name: Upload package artifacts
        uses: actions/upload-artifact@main
        with:
          name: |
            - macOS
          path: |
            build/TigerVNC-*.dmg
            
