name: Build

on: [workflow_dispatch, push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code 😂
        uses: actions/checkout@main
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get full-upgrade -yqqqfm --autoremove --purge
          sudo apt-get install -yqqqfm --autoremove --purge libfltk1.3-dev fluid gettext appstream
          sudo apt-get install -yqqqfm --autoremove --purge libgnutls28-dev nettle-dev libgmp-dev
          sudo apt-get install -yqqqfm --autoremove --purge libxtst-dev libxdamage-dev libxfixes-dev libxrandr-dev libpam-dev
          sudo apt-get install -yqqqfm --autoremove --purge libavcodec-dev libavutil-dev libswscale-dev
          sudo apt-get clean

      - name: Configure
        run: cmake -DCMAKE_BUILD_PARALLEL_LEVEL=128 -DCMAKE_BUILD_TYPE=RelWithDebInfo -S . -B build
      - name: Build
        working-directory: build
        run: make -j 128
      - name: Install
        working-directory: build
        run: make tarball
      - uses: actions/upload-artifact@main
        with:
          name: Linux (Ubuntu)
          path: build/tigervnc-*.tar.gz

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout Code 😂
        uses: actions/checkout@main
      - uses: msys2/setup-msys2@v2
      - name: Install dependencies
        run: |
          pacman --sync --noconfirm --needed \
            make mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-arm64-toolchain mingw-w64-arm64-cmake
          pacman --sync --noconfirm --needed \
            mingw-w64-x86_64-fltk mingw-w64-x86_64-libjpeg-turbo \
            mingw-w64-x86_64-gnutls mingw-w64-x86_64-pixman \
            mingw-w64-x86_64-nettle mingw-w64-x86_64-gmp \
            mingw-w64-aarch64-fltk mingw-w64-aarch64-libjpeg-turbo \
            mingw-w64-aarch64-gnutls mingw-w64-aarch64-pixman \
            mingw-w64-aarch64-nettle mingw-w64-aarch64-gmp
      - name: Configure
        run: cmake -DCMAKE_BUILD_PARALLEL_LEVEL=128 -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -S . -B build
      - name: Build
        working-directory: build
        run: make -j 128
      - name: Install
        working-directory: build
        env:
          MSYS2_PATH_TYPE: inherit
        run: make -j 128 installer winvnc_installer
      - uses: actions/upload-artifact@main
        with:
          name: Windows
          path: build/release/tigervnc*.exe

  build-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: |
          brew install fltk pixman ffmpeg
          brew install gnutls nettle gmp
      - name: Configure
        run: cmake -DCMAKE_BUILD_PARALLEL_LEVEL=128 -DCMAKE_BUILD_TYPE=Release -S . -B build
      - name: Build
        working-directory: build
        run: make -j 128
      - name: Install
        working-directory: build
        run: make dmg
      - uses: actions/upload-artifact@main
        with:
          name: macOS
          path: build/TigerVNC-*.dmg

  build-java:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ '16', '18', '19' ]
    steps:
      - uses: actions/checkout@main
      - name: Setup java
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Configure
        working-directory: java
        run: cmake -DCMAKE_BUILD_PARALLEL_LEVEL=128 -DCMAKE_BUILD_TYPE=Release -S . -B build
      - name: Build
        working-directory: java/build
        run: make -j 128
      - uses: actions/upload-artifact@main
        with:
          name: Java (${{ matrix.java }})
          path: java/build/VncViewer.jar

  build-packages:
    strategy:
      matrix:
        target:
          - centos-latest
          - ubuntu-latest
      fail-fast: false
    runs-on: ubuntu-22.04
    env:
      DOCKER: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@main
      - name: Build image
        run: docker build -t tigervnc/$DOCKER .github/containers/$DOCKER
      - name: Build packages
        run: .github/containers/$DOCKER/build.sh
      - uses: actions/upload-artifact@main
        with:
          name: Packages (${{ matrix.target }})
          path: .github/containers/${{ matrix.target }}/result
